### ISSUE TITLE
Source Code ASReview Datatool Dedup

### ISSUE THREAD

**Issue by Kirsten-Ziesemer** [asreview/asreview-datatools#31]
Hi all, thank you for the new addition to the ASReview Datatool-set! Could you navigate me to the source code of the deduplication method. For a deduplication-project we are looking into different deduplication methods and I would like to add and test the performance of the ASReview Datatool dedup. TIA

**Comment by gimoAI** [comment]
Hi @Kirsten-Ziesemer, interesting project, the source code can be found [here](https://github.com/asreview/asreview/blob/master/asreview/data/base.py#L461-L505).
