### ISSUE TITLE
Snowballing test hits rate limit of OpenAlex (HTTP 429)

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview-datatools#43]
The unit tests in https://github.com/asreview/asreview often return 429 errors on the snowballing test. Let's look for a smaller test and use the polite pool.

**Comment by J535D165** [comment]
Temporarily disabled this GA workflow in https://github.com/asreview/asreview/commit/ffb7182843ad5d3cca2ccb3355b13de92bd097a3.

**Comment by PeterLombaers** [comment]
Fixed by #44
